global:
    slack_api_url: '<slack_webhook_url>'
templates:
    - '/etc/alertmanager-templates/*.tmpl'
route:
    receiver: 'rancherlas'
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 30s
receivers:
    - name: 'rancherlas'
      slack_configs:
      - channel: '#alerts'